import type { Config } from "tailwindcss";
import colors from "tailwindcss/colors";

const config: Config = {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      "brand-base": "var(--brand-base-purple)",
      "brand-accent": "var(--brand-accent-purple)",
      "brand-accent-light": "var(--brand-accent-light)",
      "brand-cream": "var(--brand-cream-bg)",
      "brand-text-dark": "var(--brand-dark-text)",
      "token-bg": "var(--token-bg-main)",
      "token-card": "var(--token-bg-card)",
      "token-card-soft": "var(--token-bg-card-soft)",
      "token-header": "var(--token-bg-header)",
      "token-text": "var(--token-text-primary)",
      "token-text-secondary": "var(--token-text-secondary)",
      "token-text-muted": "var(--token-text-muted)",
      "token-accent": "var(--token-accent)",
      "token-accent-soft": "var(--token-accent-soft)",
      "token-accent-bg": "var(--token-accent-bg)",
      "token-border": "var(--token-border-card)",
      "token-divider": "var(--token-divider)",
      red: colors.red,
      green: colors.green,
      blue: colors.blue,
      yellow: colors.yellow,
      orange: colors.orange,
      black: colors.black,
      white: colors.white,
      transparent: "transparent",
      current: "currentColor",
      border: "hsl(var(--border))",
      input: "hsl(var(--input))",
      ring: "hsl(var(--ring))",
      background: "hsl(var(--background))",
      foreground: "hsl(var(--foreground))",
      primary: {
        DEFAULT: "hsl(var(--primary))",
        foreground: "hsl(var(--primary-foreground))",
      },
      secondary: {
        DEFAULT: "hsl(var(--secondary))",
        foreground: "hsl(var(--secondary-foreground))",
      },
      destructive: {
        DEFAULT: "hsl(var(--destructive))",
        foreground: "hsl(var(--destructive-foreground))",
      },
      muted: {
        DEFAULT: "hsl(var(--muted))",
        foreground: "hsl(var(--muted-foreground))",
      },
      accent: {
        DEFAULT: "hsl(var(--accent))",
        foreground: "hsl(var(--accent-foreground))",
      },
      popover: {
        DEFAULT: "hsl(var(--popover))",
        foreground: "hsl(var(--popover-foreground))",
      },
      card: {
        DEFAULT: "hsl(var(--card))",
        foreground: "hsl(var(--card-foreground))",
      },
      surna: {
        red: "hsl(var(--surna-red))",
        "red-light": "hsl(var(--surna-red-light))",
        "red-dark": "hsl(var(--surna-red-dark))",
        surface: "hsl(var(--surna-surface))",
        elevated: "hsl(var(--surna-elevated))",
        border: "hsl(var(--surna-border))",
        coral: "var(--surna-coral)",
        "coral-light": "var(--surna-coral-light)",
        gold: "var(--surna-gold)",
        "gold-pin": "var(--surna-gold-pin)",
        "blue-link": "var(--surna-blue-link)",
        pro: "var(--surna-pro)",
        purple: "var(--surna-pro)",
        "ios-red": "var(--surna-ios-red)",
        outline: "var(--surna-outline)",
      },
      chart: {
        "1": "hsl(var(--chart-1))",
        "2": "hsl(var(--chart-2))",
        "3": "hsl(var(--chart-3))",
        "4": "hsl(var(--chart-4))",
        "5": "hsl(var(--chart-5))",
      },
      sidebar: {
        DEFAULT: "hsl(var(--sidebar))",
        foreground: "hsl(var(--sidebar-foreground))",
        primary: "hsl(var(--sidebar-primary))",
        "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
        accent: "hsl(var(--sidebar-accent))",
        "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
        border: "hsl(var(--sidebar-border))",
        ring: "hsl(var(--sidebar-ring))",
      },
    },
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "token-card": "var(--token-radius-card)",
        "token-button": "var(--token-radius-button)",
        "token-bubble": "var(--token-radius-bubble)",
        "token-small": "var(--token-radius-small)",
        "token-micro": "var(--token-radius-micro)",
        "token-pill": "var(--token-radius-pill)",
      },
      spacing: {
        "token-xs": "var(--token-spacing-xs)",
        "token-s": "var(--token-spacing-s)",
        "token-m": "var(--token-spacing-m)",
        "token-l": "var(--token-spacing-l)",
        "token-xl": "var(--token-spacing-xl)",
        "token-xxl": "var(--token-spacing-xxl)",
      },
      boxShadow: {
        "token-card": "var(--token-shadow-card)",
        "token-card-hover": "var(--token-shadow-card-hover)",
        "token-modal": "var(--token-shadow-modal)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-1000px 0" },
          "100%": { backgroundPosition: "1000px 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
        "scale-in": "scaleIn 0.2s ease-out",
        shimmer: "shimmer 2s infinite linear",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};

export default config;
